'use client'
import Head from 'next/head'
import Button from '@mui/material/Button'
import axios from 'axios'
import { useEffect } from 'react'
import { Box, useTheme } from '@mui/material'
import { useSettings } from 'src/hooks/useSettings'
import CustomTextField from 'src/components/text-field'

export default function Home() {
  // const fetchApiUser = async () => {
  //   await axios.get('http://localhost:3001/api/users?limit=10&page=1&order=created%20asc').then(res => {
  //     console.log(res)
  //   })
  // }

  // useEffect(() => {
  //   fetchApiUser()
  // }, [])

  const theme = useTheme()
  const { settings } = useSettings()
  console.log(theme)
  console.log(settings)

  return (
    <>
      <Head>
        <title>Lập trình thật dễ</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <Box sx={{ margin: 6, width: '200px' }}>
        <CustomTextField id='outlined-multiline-flexible' label='Multiline' />
      </Box>
    </>
  )
}
